Console.WriteLine("Минимальные и максимальные значения CTS переменных: ");
Console.WriteLine("----------");
Console.WriteLine("Целочисленные типы данных");
Console.WriteLine($"byte: min = {byte.MinValue}, max = {byte.MaxValue}");
Console.WriteLine($"sbyte: min = {sbyte.MinValue}, max = {sbyte.MaxValue}");
Console.WriteLine($"short: min = {short.MinValue}, max = {short.MaxValue}");
Console.WriteLine($"ushort: min = {ushort.MinValue}, max = {ushort.MaxValue}");
Console.WriteLine($"int: min = {int.MinValue}, max = {int.MaxValue}");
Console.WriteLine($"uint: min = {uint.MinValue}, max = {uint.MaxValue}");
Console.WriteLine($"long: min = {long.MinValue}, max = {long.MaxValue}");
Console.WriteLine($"ulong: min = {ulong.MinValue}, max = {ulong.MaxValue}");
Console.WriteLine("----------");
Console.WriteLine("Типы данных с плавающей точкой");
Console.WriteLine($"float: min = {float.MinValue}, max = {float.MaxValue}");
Console.WriteLine($"double: min = {double.MinValue}, max = {double.MaxValue}");
Console.WriteLine($"decimal: min = {decimal.MinValue}, max = {decimal.MaxValue}");
Console.WriteLine("----------");
Console.WriteLine("Символьный тип данных");
Console.WriteLine($"char: min = {char.MinValue}, max = {char.MaxValue}");
Console.WriteLine("----------");
Console.WriteLine("Логический тип данных");
Console.WriteLine($"bool: min = false, max = true");
Console.WriteLine("----------");
Console.WriteLine("Тип данных null");
Console.WriteLine($"Null: null");
